# browser config
browser: "chrome"

# project and staging config
portal_page: "http://test-blizko.ru" # Главная портала
normal_user_mail: "crow1@gmail.com" # Email Обычного пользователя
normal_user_pwd: "0000" # Пароль обычного пользователя
super_user_mail: "sunlf@yandex.ru" # SU email
super_user_pwd: "82718951" # SU pass
<<<<<<< HEAD
super_user_enter_url: "http://all.test-blizko.ru/users/?uk=ba8dcf5c90717671751e749c0aab4b2c" # Прямая ссылка на вход через СЮ пользователя

=======
super_user_enter_url: "http://all.test-blizko.ru/users/?uk=ba8dcf5c90717671751e749c0aab4b2c" #Прямая ссылка на вход через СЮ пользователя
<<<<<<< HEAD
>>>>>>> 67513e4... Add super_user_enter_url in config
=======

>>>>>>> 0b6c0c4... Add super_user_enter_url v.2
# other parameters


# hardcoded parameters
