portal_page_url: 'http://test2-blizko.ru'
default_company: 'http://crowfarm.test2-blizko.ru'
empty_company: 'http://msk.test2-blizko.ru/firms/14094493'

populated_listing_link: '/predl/promgood/appliances/tehnikadljadoma/pylesos'
