portal_page_url: 'http://test-blizko.ru'
default_company: 'http://crowfarm-108.test-blizko.ru'
empty_company: 'http://www.test-blizko.ru/firms/8650839'

populated_listing_link: '/predl/transport/zhd_vodnyy_vozdushnyy_transport/water_transport/lodki_bajdarki_kanoe/17708'
