portal_page_url: 'http://test4-blizko.ru'
default_company: 'http://crowfarm-1.test4-blizko.ru'
empty_company: 'http://www.test4-blizko.ru/firms/25775'

populated_listing_link: '/predl/promgood/appliances/tehnikadljadoma/pylesos'
