portal_page_url: 'http://test3-blizko.ru'
default_company: 'http://crowfarm-2.test3-blizko.ru'
empty_company: 'http://msk.test3-blizko.ru/firms/14094493'

populated_listing_link: '/predl/promgood/appliances/tehnikadljadoma/pylesos'
